openapi: 3.0.1
info:
  title: solutions-enabler9
  description: Run solutions-enabler9 in Direktiv
  version: "1.0"
  x-direktiv-meta:
    container: gcr.io/direktiv/functions/solutions-enabler9
    maintainer: "[direktiv.io](https://www.direktiv.io) "
    issues: https://github.com/direktiv-apps/solutions-enabler9/issues
    url: https://github.com/direktiv-apps/solutions-enabler9
    categories:
    - infrastructure
    license: "[Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0)"
    long-description: "This function provides EMC's Solutions Enabler CLI version\
      \ 9.2.3.4. The only default environment variable set is SYMCLI_OFFLINE.\n\n\
      It uses a `netcnfg` file in the working directory and copies it to the target\
      \ location `/usr/emc/API/symapi/config/netcnfg`.  This approach means that this\
      \ function can not be run in parallel with different netcnfg configurations\
      \ and therefore can not  be used as namespace service or with different configurations\
      \ within a workflow. \n\nThe `netcnfg` file can be provided as workflow or namespace\
      \ variable as well as direktiv file in the function payload."
servers:
- url: /
paths:
  /:
    post:
      parameters:
      - name: Direktiv-ActionID
        in: header
        description: "direktiv action id is an UUID. \nFor development it can be set\
          \ to 'development'\n"
        schema:
          type: string
          default: development
      - name: Direktiv-TempDir
        in: header
        description: |
          direktiv temp dir is the working directory for that request
          For development it can be set to e.g. '/tmp'
        schema:
          type: string
          default: /tmp
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                files:
                  type: array
                  description: File to create before running commands.
                  items:
                    $ref: '#/components/schemas/direktivFile'
                commands:
                  type: array
                  description: Array of commands.
                  items:
                    type: object
                    properties:
                      command:
                        type: string
                        description: Command to run
                      silent:
                        type: boolean
                        description: If set to false the command will not print output
                          to logs.
                        default: false
                      print:
                        type: boolean
                        description: If set to false the command will not print the
                          full command with arguments to logs.
                        default: true
                      continue:
                        type: boolean
                        description: "Stops excecution if command fails, otherwise\
                          \ proceeds with next command"
                      envs:
                        type: array
                        description: Environment variables set for each command.
                        example:
                        - name: SYMCLI_CONNECT_TYPE
                          value: REMOTE
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                              description: Name of the variable.
                            value:
                              type: string
                              description: Value of the variable.
        required: false
      responses:
        "200":
          description: List of executed commands.
          content:
            application/json:
              schema:
                type: object
                properties:
                  solutions-enabler9:
                    type: array
                    items:
                      required:
                      - result
                      - success
                      type: object
                      properties:
                        success:
                          type: boolean
                        result:
                          type: object
            solutions-enabler9:
              example:
              - result:
                  SymCLI_ML:
                    Network_Service:
                      name: SYMAPI_SERVER
                      node_address: 12.345.67.89
                      node_name: node001
                      node_port: "7777"
                      node_seclevel: ANY
                      pairing_method: Single
                      type: TCPIP
                success: true
        default:
          description: generic error response
          headers:
            Direktiv-ErrorMessage:
              schema:
                type: string
            Direktiv-ErrorCode:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      x-direktiv-function: |-
        functions:
        - id: solutions-enabler9
          image: gcr.io/direktiv/functions/solutions-enabler9:1.0
          type: knative-workflow
      x-direktiv-examples:
      - title: Basic
        content: "- id: solutions-enabler9\n  type: action\n  action:\n    function:\
          \ solutions-enabler9\n    input: \n      files:\n      - name: netcnfg\n\
          \        data: SYMAPI_SERVER - TCPIP node001 12.345.67.89 7777 ANY\n   \
          \   commands:\n      - command: symcfg -services list\n      envs:\n   \
          \   - name: SYMCLI_OFFLINE\n        value: 1"
      - title: JSON output
        content: "- id: solutions-enabler9\n  type: action\n  action:\n    function:\
          \ solutions-enabler9\n    input: \n      files:\n      - name: netcnfg\n\
          \        data: SYMAPI_SERVER - TCPIP node001 12.345.67.89 7777 ANY\n   \
          \   commands:\n      - command: bash -c 'symcfg -services list -output xml_element\
          \ | xq .'"
      x-direktiv:
        cmds:
        - action: exec
          exec: cp netcnfg /usr/emc/API/symapi/config/netcnfg
          silent: true
          print: false
        - action: foreach
          loop: .Commands
          exec: "{{ .Item.Command }}"
          silent: "{{ .Item.Silent }}"
          print: "{{ .Item.Print }}"
          continue: "{{ .Item.Continue }}"
          runtime-envs: |
            [
            {{- range $index, $element := .Item.Envs }}
            {{- if $index}},{{- end}}
            "{{ $element.Name }}={{ $element.Value }}"
            {{- end }}
            ]
        output: |
          {
            "solutions-enabler9": {{ index . 1 | toJson }}
          }
      x-direktiv-errors:
        io.direktiv.command.error: Command execution failed
        io.direktiv.output.error: Template error for output generation of the service
        io.direktiv.ri.error: Can not create information object from request
      x-codegen-request-body-name: body
components:
  schemas:
    direktivFile:
      type: object
      x-go-type:
        type: DirektivFile
        import:
          package: github.com/direktiv/apps/go/pkg/apps
    error:
      required:
      - errorCode
      - errorMessage
      type: object
      properties:
        errorCode:
          type: string
        errorMessage:
          type: string

